apiVersion: v1
kind: Service
metadata:
  name: app
  annotations:
    # kubernetes.io/ingress.allow-http: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:419412945238:certificate/542add24-4a54-4151-a2ff-65f594d4eb4f
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    #service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "env=staging,group=alta,project=alta-demo,sub-project=app"
spec:
  selector:
    name: app
  type: LoadBalancer
  ports:
   -  name: http
      protocol: TCP
      port: 80
      targetPort: 80