"""empty message

Revision ID: 4c4ee3f8ee4d
Revises: 920362da96d5
Create Date: 2020-01-13 17:40:18.143289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4ee3f8ee4d'
down_revision = '920362da96d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartDetail', sa.Column('jumlah_item', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartDetail', 'jumlah_item')
    # ### end Alembic commands ###
