"""empty message

Revision ID: af2614a3ce9c
Revises: 2db97444904a
Create Date: 2020-01-05 10:49:20.360131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2614a3ce9c'
down_revision = '2db97444904a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nama', table_name='product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('nama', 'product', ['nama'], unique=True)
    # ### end Alembic commands ###
