"""empty message

Revision ID: d464d3e7819c
Revises: 
Create Date: 2020-01-05 04:08:53.320808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd464d3e7819c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('nama_lengkap', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('no_hp', sa.String(length=13), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'no_hp')
    op.drop_column('users', 'nama_lengkap')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
